[package]
name = "proxmox-api-macro"
edition = "2018"
version = "0.3.3"
authors = [ "Wolfgang Bumiller <w.bumiller@proxmox.com>" ]
license = "AGPL-3"
description = "Proxmox API macro"

exclude = [ "debian" ]

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = [ "extra-traits", "full", "visit-mut" ] }

[dev-dependencies]
futures = "0.3"
proxmox = { version = "0.11.0", path = "../proxmox", features = [ "test-harness", "api-macro" ] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

# [features]
# # Used to quickly filter out the serde derive noise when using `cargo expand` for debugging!
# # Add this in case you need it, but don't commit it (to avoid debcargo picking this up)!
# noserde = []
